### ISSUE TITLE
File descriptor exhasution when creating many pingers

### ISSUE THREAD

**Issue by jkilpatr** [bparli/fastping-rs#12] opened 2020-04-06 16:01 UTC
If you modify the main code example to work as follows, you will find that the number of file descriptors used by this example only ever increases.

https://github.com/jkilpatr/pinger-descriptor-exhaustion

I think this means the drop implementation for the pinger is missing some cleanup component.

**Comment by bparli** [comment] 2020-04-11 17:37
Hey @jkilpatr, that is true; background listener threads are spawned when you create a new pinger.

The question is why would you want to create multiple pingers? By design, you should only need one.  Maybe there is another way to address what you're trying to accomplish

**Comment by bparli** [comment] 2020-08-13 20:00
Going to close this but let me know if you run into anymore confusions @jkilpatr

**Comment by apognu** [comment] 2021-02-10 10:03
@bparli I'm sorry about unearthing this closed issue, but I too have an issue with file descriptors are not being closed when `Pinger` goes out of scope.

My use case is I have a product with a lot of independently-running threads/tasks that may or may not each run a ping depending on their configuration. To be more precise, I am working on some kind of uptime monitoring tool, which may contain hundreds of checks, not all of the ICMP type, so some may use `Pinger`, some might not, and only when a check is required. When an ICMP check needs to be run, a task for that check is created, which created a `Pinger` and emits one echo request.

Currently, the behavior is that over time (and an uptime checker should be a very long-running process), the number of opened file descriptors skyrockets.

I understand if this might be out of scope for this crate, but keeping file descriptors open when the owning struct goes out of scope might not be the best behavior whatever the use case.

**Comment by bparli** [comment] 2021-02-26 22:23
hey @apognu let me look into this again.  IIRC `pnet`  (the crate this one is built on) does implement a drop trait on file descriptors so will double check that and try to reproduce (as time allows)

**Comment by bparli** [comment] 2021-03-02 05:31
Thanks for raising this again @apognu; it should be fixed in v0.2.2.  I'll leave this issue open in case you'd like to verify

**Closed as completed** 2021-04-03 17:13 UTC

**Comment by tubzby** [comment] 2023-11-03 07:00
@bparli is it break for version 0.2.4? 

It's probably caused by `start_listener` not handling `stop` correctly, each time it will leak 2 FDs and 2 threads.

**Comment by tubzby** [comment] 2023-11-03 07:18
We should probably use `iter.next_with_timeout()` instead of `iter.next()`.
